$wallpaper = /home/amos/.config/wallpapers/a_building_with_a_flag_on_the_roof.jpg

$background = rgb(10131a)
$foreground = rgb(e0e2ec)

$color0 = rgb(0b0e15)
$color1 = rgb(aac7ff)
$color2 = rgb(afc7f7)
$color3 = rgb(f0b0ff)
$color4 = rgb(4090fe)
$color5 = rgb(2e4770)
$color6 = rgb(c46ede)
$color7 = rgb(c1c6d5)
$color8 = rgb(8b919f)
$color9 = rgb(aac7ff)
$color10 = rgb(afc7f7)
$color11 = rgb(f0b0ff)
$color12 = rgb(4090fe)
$color13 = rgb(2e4770)
$color14 = rgb(c46ede)
$color15 = rgb(e0e2ec)
